name: Build & Quality Checks

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

    steps:
#      - name: Debug env
#        run: 'printf "KEY LENGTH: %s\n" "${#NVD_API_KEY}"'

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Dependency-Check DB
        uses: actions/cache@v5
        with:
          path: |
            ~/.cache/dependency-check
            ~/.m2/repository/org/owasp/dependency-check-data
          key: dc-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            dc-${{ runner.os }}-
          
#      - name: Debug Maven env
#        run: ./mvnw -q help:evaluate -Dexpression=nvd.api-key -DforceStdout

#      - name: Debug Maven property length
#        run: |
#          VAL=$(./mvnw -q help:evaluate -Dexpression=nvd.api-key -DforceStdout)
#          echo "LEN=${#VAL}"
        
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 20

      - name: Cache Maven
        uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}

      - name: Cache Yarn
        uses: actions/cache@v5
        with:
          path: |
            ~/.cache/yarn
            node_modules
          key: yarn-${{ hashFiles('**/yarn.lock', '**/package.json') }}

      - name: Install dependencies (npm audit)
        run: |
          yarn install
          yarn audit --groups dependencies || true

      - name: Build plugin (Maven)
        run: ./mvnw -B clean install

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v6
        with:
          name: activemq-classic-plugin
          path: target/*.jar
